jak metriky fungují. 

[1 1 1]
[1 1 0]
[1 0 1]
[1 0 0]
[0 0 0]
[0 0 1]
[0 1 0]
[0 1 1]


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance

Euclidean distance

In [33]:
a=[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b=[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
print('1)', distance.euclidean(a, b))
print('2)', distance.euclidean([1, 1, 1], [1, 0, 1]))
print('3)', distance.euclidean([1, 1, 1], [1, 0, 0]))
print('4)', distance.euclidean([1, 1, 1], [1, 1, 0]))
print('5)', distance.euclidean([1, 1, 1], [0, 0, 0]))
print('6)', distance.euclidean([1, 1, 1], [0, 0, 1]))
print('7)', distance.euclidean([1, 1, 1], [0, 1, 0]))
print('8)', distance.euclidean([1, 1, 1], [0, 1, 1]))


1) 3.3166247903554
2) 1.0
3) 1.4142135623730951
4) 1.0
5) 1.7320508075688772
6) 1.4142135623730951
7) 1.4142135623730951
8) 1.0


Manhattan distance

In [3]:
a=[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
b=[]
print('1)', distance.cityblock(a, b))
print('1)', distance.cityblock([1, 1, 1], [1, 1, 0]))
print('2)', distance.cityblock([1, 1, 1], [1, 0, 1]))
print('3)', distance.cityblock([1, 1, 1], [1, 0, 0]))
print('4)', distance.cityblock([1, 1, 1], [1, 1, 0]))
print('5)', distance.cityblock([1, 1, 1], [0, 0, 0]))
print('6)', distance.cityblock([1, 1, 1], [0, 0, 1]))
print('7)', distance.cityblock([1, 1, 1], [0, 1, 0]))
print('8)', distance.cityblock([1, 1, 1], [0, 1, 1]))

1) 11
1) 1
2) 1
3) 2
4) 1
5) 3
6) 2
7) 2
8) 1


Chebyshev distance

In [27]:
print('1)', distance.chebyshev([1, 1, 1], [1, 1, 0]))
print('2)', distance.chebyshev([1, 1, 1], [1, 0, 1]))
print('3)', distance.chebyshev([1, 1, 1], [1, 0, 0]))
print('4)', distance.chebyshev([1, 1, 1], [1, 1, 0]))
print('5)', distance.chebyshev([1, 1, 1], [0, 0, 0]))
print('6)', distance.chebyshev([1, 1, 1], [0, 0, 1]))
print('7)', distance.chebyshev([1, 1, 1], [0, 1, 0]))
print('8)', distance.chebyshev([1, 1, 1], [0, 1, 1]))

1) 1
2) 1
3) 1
4) 1
5) 1
6) 1
7) 1
8) 1


Canberra distance

In [15]:
print('1)', distance.canberra([1, 1, 1], [1, 1, 0]))
print('2)', distance.canberra([1, 1, 1], [1, 0, 1]))
print('3)', distance.canberra([1, 1, 1], [1, 0, 0]))
print('4)', distance.canberra([1, 1, 1], [1, 1, 0]))
print('5)', distance.canberra([1, 1, 1], [0, 0, 0]))
print('6)', distance.canberra([1, 1, 1], [0, 0, 1]))
print('7)', distance.canberra([1, 1, 1], [0, 1, 0]))
print('8)', distance.canberra([1, 1, 1], [0, 1, 1]))

1) 1.0
2) 1.0
3) 2.0
4) 1.0
5) 3.0
6) 2.0
7) 2.0
8) 1.0


Cosine similarity

In [17]:
print('1)', distance.cosine([1, 1, 1], [1, 1, 0]))
print('2)', distance.cosine([1, 1, 1], [1, 0, 1]))
print('3)', distance.cosine([1, 1, 1], [1, 0, 0]))
print('4)', distance.cosine([1, 1, 1], [1, 1, 0]))
print('5)', distance.cosine([1, 1, 1], [0, 0, 0]))
print('6)', distance.cosine([1, 1, 1], [0, 0, 1]))
print('7)', distance.cosine([1, 1, 1], [0, 1, 0]))
print('8)', distance.cosine([1, 1, 1], [0, 1, 1]))

1) 0.18350341907227397
2) 0.18350341907227397
3) 0.42264973081037427
4) 0.18350341907227397
5) 0
6) 0.42264973081037427
7) 0.42264973081037427
8) 0.18350341907227397
